# Generated by Django 2.2.16 on 2020-10-20 15:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True, max_length=255)),
                ('director', models.TextField(blank=True, max_length=255)),
                ('popularity', models.FloatField(blank=True)),
                ('imdb_score', models.FloatField(blank=True)),
                ('genre', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), default=list, null=True, size=None)),
            ],
        ),
    ]
